dataset_name: default
dataset_path: TheFinAI/flare-es-multifin
output_type: classification
doc_to_target: '{{polarity}}'
doc_to_text: '{{sentence}} (Target: {{target}})'
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{sentence}} (Target: {{target}})"
generation_kwargs:
  do_sample: false
  temperature: 0.0
  max_gen_toks: 10
metric_list:
  - metric: !function metrics.macro_f1_score
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
task: JPchABSA
tag: jp
test_split: test
